name: flutter_instagram
description: A Instagram Clone App project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.3.11
  firebase_messaging: ^11.2.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  firebase_core: ^1.13.1
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2
  simple_animations: ^4.0.1
  awesome_icons: ^1.1.0
  image_picker: ^0.8.4+11
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  http: ^0.13.4
  lottie: ^1.2.2
#  camera: ^0.9.4+16
  flutter_local_notifications: ^9.4.0

  device_info_plus: ^3.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/anime/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf